### ISSUE TITLE
Jonathan

### ISSUE THREAD

**Issue by Sydow75** [SANDQVISTT/FilmRecensionSite#21]
###                                    Jonathan Sandqvist 

Utbildar mig just nu till front/end utveckling som hoppas tar mig till framtida utmaningar som utvecklare.
Versionshantering har lärt mig hur vi ska arbeta i grupp och att använda en klient för att sammanfatta vårt arbete vi håller på med.
_Jonathan Sandqvist_

**Comment by SANDQVISTT** [comment]
DONE
